car_django/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import (
    LoginView,
    RegisterView,
    error_login_view,
    come_back_to_main_page, 
)


from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from booking.views import BookingDeleteView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LoginView.as_view(), name="login"),
    path("error_login", error_login_view, name="error_login"),
    path("", come_back_to_main_page, name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("main/", include("main.urls")),
    path("main/booking/", include("booking.urls")),
    path("main/opinion/", include("opinion.urls")),
    path("main/contact/", include("contact.urls")),
    path("main/aboutus/", include("aboutus.urls")),
    path('main/delete/<int:booking_id>/', BookingDeleteView.as_view(), name='booking_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import main_view

urlpatterns = [
    path("", main_view, name="main"),
]

opinion/urls.py
from django.urls import path
from .views import opinion_view, add_opinion

urlpatterns = [
    path("", opinion_view, name="opinions"),
     path("add/", add_opinion, name="add_opinion"),
    
]

opinion/models.py
from django.db import models
from booking.models import Booking
from django.contrib.auth.models import User

# Create your models here.
class Opinion(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Opinia od {self.user} oceniona na {self.rating}"

opinion/forms.py
from django import forms
from .models import Opinion
from booking.models import Booking

class OpinionForm(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = ['booking', 'rating', 'comment']
        widgets = {
            'booking': forms.Select(attrs={'class': 'form-control'}),
            'rating': forms.RadioSelect(attrs={'class': 'form-check-input'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

opinion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import OpinionForm
from django.http import JsonResponse
from .models import Opinion
import json
from booking.models import Booking
from rest_framework_simplejwt.tokens import AccessToken
from django.contrib.auth.models import User

# Create your views here.
def opinion_view(request):
    # pusty formularz
    form = OpinionForm()  

    opinions = Opinion.objects.all().select_related("booking", "user")
    return render(request, 'opinion.html', {'form': form, 'opinions': opinions})


def add_opinion(request):
    if request.method == 'POST':
        try:

            data = json.loads(request.body)
            booking_id = data.get('booking')  # ID rezerwacji
            rating = data.get('rating')  # Ocena
            comment = data.get('comment')  # Komentarz
            access_token = request.headers.get('Authorization') 

            print(f"Dane: booking_id={booking_id}, rating={rating}, comment={comment}")
            
            if not access_token:
                return JsonResponse({
                    'success': False,
                    'message': 'Musisz być zalogowany, aby dodać opinię.'
                })

            access_token = access_token.split(' ')[1]

            # Weryfikacja tokenu
            try:
                token = AccessToken(access_token)
                user_id = token['user_id']  
                user = User.objects.get(id=user_id)  
            except Exception as e:
                print(f"Błąd podczas weryfikacji tokenu: {str(e)}")
                return JsonResponse({
                    'success': False,
                    'message': 'Niepoprawny token, użytkownik nie jest zalogowany.'
                })

            # czy wszystkie dane zostały przekazane
            if not all([booking_id, rating, comment]):
                return JsonResponse({
                    'success': False,
                    'message': 'Wszystkie pola są wymagane.'
                })

            # Sprawdzam, czy rezerwacja z takim booking_id istnieje
            try:
                booking = Booking.objects.get(id=booking_id)
            except Booking.DoesNotExist:
                return JsonResponse({
                    'success': False,
                    'message': 'Nie znaleziono rezerwacji o podanym ID.'
                })

            # Sprawdzam, czy użytkownik już dodał opinię do tej rezerwacji
            if Opinion.objects.filter(booking=booking, user=user).exists():
                return JsonResponse({
                    'success': False,
                    'message': 'Już dodałeś opinię do tej rezerwacji.'
                })

            # Formularz z danymi
            form = OpinionForm({
                'booking': booking,
                'rating': rating,
                'comment': comment
            })

            # Sprawdzam, czy formularz jest prawidłowy
            if form.is_valid():
                opinion = form.save(commit=False)
                opinion.user = user 
                opinion.save()  
                print(f"Opinia zapisana: {opinion}")

                return JsonResponse({
                    'success': True,
                    'message': 'Opinia została dodana pomyślnie!'
                })

            else:
                errors = form.errors.as_json()  
                print(f"Błędy formularza: {errors}")
                return JsonResponse({
                    'success': False,
                    'message': 'Formularz zawiera błędy.',
                    'errors': errors
                })

        except json.JSONDecodeError:
            print(f"Błędny format danych: {request.body}")
            return JsonResponse({
                'success': False,
                'message': 'Błędny format danych.'
            })

        except Exception as e:
            print(f"Błąd: {str(e)}")
            return JsonResponse({
                'success': False,
                'message': f'Wystąpił błąd: {str(e)}'
            })

    # Jeśli metoda HTTP to nie POST
    return JsonResponse({
        'success': False,
        'message': 'Błąd połączenia.'
    })

opinion/templates/opinion.html
{% extends 'index.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'opinion.css' %}" />
{% endblock %} {% block content %}
<div class="opinionWrapper">
  <img
    class="car-image kenburns-top"
    src="{% static 'img/auto_opinion.jpg' %}"
    alt="Audi"
  />
  <form action="{% url 'main' %}" method="get">
    <div style="--clr: #ff5722">
      <button type="submit">Powrót</button>
    </div>
  </form>

  <div class="container mt-5 addOpinion">
    <h1 style="color: #ff5722">Opinie</h1>

    <h3 style="color: #ff5722">Dodaj opinię</h3>

    <form id="opinion-form" method="POST" action="{% url 'add_opinion' %}">
      {% csrf_token %}

      <div class="mb-3">
        <label style="color: #ff5722; font-size: 1.8rem" for="id_booking"
          >Wybierz samochód</label
        >
        {{ form.booking }}
      </div>

      <label
        style="color: #ff5722; font-size: 1.8rem; margin-right: 10px"
        for="id_rating"
        >Wybierz ocenę</label
      >
      <div
        style="
          display: flex;
          justify-content: flex-start;
          flex-direction: row;
          gap: 10px;
          color: #ff5722;
        "
      >
        <label for="rating-1">
          <input type="radio" id="rating-1" name="rating" value="1" /> 1
        </label>
        <label for="rating-2">
          <input type="radio" id="rating-2" name="rating" value="2" /> 2
        </label>
        <label for="rating-3">
          <input type="radio" id="rating-3" name="rating" value="3" /> 3
        </label>
        <label for="rating-4">
          <input type="radio" id="rating-4" name="rating" value="4" /> 4
        </label>
        <label for="rating-5">
          <input type="radio" id="rating-5" name="rating" value="5" /> 5
        </label>
      </div>

      <div class="mb-3">
        <label style="color: #ff5722; font-size: 1.8rem" for="id_comment"
          >Twój komentarz</label
        >
        {{ form.comment }}
      </div>

      <button style="background-color: #ff5722" type="submit">
        Dodaj opinię
      </button>
    </form>
  </div>

  <div class="container-card">
    <div class="container-user">
      <div class="container-opinion-user">
        {% for opinion in opinions %}
        <div class="container-box">
          <div class="container-item">
            <div class="container-header-user">
              <h2 class="container-header">{{ opinion.user }}</h2>

              {% load rating %}
              <div class="rating opinion__box-wrapper--container---rating">
                {{ opinion.rating }} {% for i in 5|to %}
                <span class="star {% if i <= opinion.rating %}filled{% endif %}"
                  >★</span
                >
                {% endfor %}
              </div>
            </div>

            <div class="container-header-user">
              <p class="car">
                Samochód:
                <span style="color: #333">{{ opinion.booking }} </span>
              </p>
            </div>

            <div class="container-under">
              <div class="container-under-first">
                {% if opinion.rating == 1 %}
                <span>Bardzo niezadowolony klient</span>
                {% elif opinion.rating == 2 %}
                <span>Niezadowolony, ale nie tragicznie</span>
                {% elif opinion.rating == 3 %}
                <span>Średnia jakość usługi, poprawić</span>
                {% elif opinion.rating == 4 %}
                <span>Zadowolony, polecam serdecznie</span>
                {% elif opinion.rating == 5 %}
                <span>Absolutnie fantastyczna jakość</span>
                {% endif %}
              </div>
              <p class="container-under-second">{{ opinion.comment }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% block extra_js %}
<script src="{% static 'js/opinion.js' %}"></script>
{% endblock %} {% endblock %}